return {
  -- ─── C/C++ LSP + Treesitter (for IoT / embedded / PlatformIO) ────────────
  {
    "mason-org/mason-lspconfig.nvim",
    opts = { ensure_installed = { "clangd" } },
  },
  {
    "nvim-treesitter/nvim-treesitter",
    opts = { ensure_installed = { "c", "cpp", "cmake" } },
  },

  -- ─── PlatformIO — IoT / Embedded Development ─────────────────────────────
  -- Supports: ESP32 (all variants), Arduino, STM32, Raspberry Pi Pico
  -- Requires: pip install platformio
  --
  -- First-time project setup:
  --   1. <leader>ioi  — init (board picker → selects framework automatically)
  --   2. Write code in src/main.cpp
  --   3. <leader>ioc  — generate compile_commands.json (run once, or after adding libs)
  --   4. <leader>iog  — generate .clangd (run once per project — kills false LSP errors)
  --   5. :LspRestart   — pick up the new .clangd
  --   6. <leader>iob  — build | <leader>iou — upload | <leader>iom — serial monitor
  --
  {
    "anurag3301/nvim-platformio.lua",
    dependencies = { "folke/snacks.nvim" },
    cmd = {
      "PioInit", "PioRun", "PioUpload", "PioMonitor",
      "PioDevices", "PioLib", "PioBoards",
    },
    keys = {
      { "<leader>io",  group  = "IoT / PlatformIO" },
      { "<leader>ioi", "<cmd>PioInit<cr>",    desc = "Init project (board picker)" },
      { "<leader>iob", "<cmd>PioRun<cr>",     desc = "Build" },
      { "<leader>iou", "<cmd>PioUpload<cr>",  desc = "Upload to device" },
      { "<leader>iom", "<cmd>PioMonitor<cr>", desc = "Serial monitor" },
      { "<leader>iod", "<cmd>PioDevices<cr>", desc = "List connected devices" },
      { "<leader>iol", "<cmd>PioLib<cr>",     desc = "Library manager" },
      { "<leader>ios", "<cmd>PioBoards<cr>",  desc = "Search boards" },
      -- Run these once per project to get proper LSP support:
      { "<leader>ioc", desc = "Generate compile_commands.json (for LSP)" },
      { "<leader>iog", desc = "Generate .clangd (suppress cross-compiler errors)" },
    },
    config = function()
      -- ── compile_commands.json ─────────────────────────────────────────────
      -- clangd needs this file to understand your project's include paths and
      -- defines. PlatformIO generates it with --target compiledb.
      vim.keymap.set("n", "<leader>ioc", function()
        Snacks.terminal("pio run --target compiledb && echo '✓ compile_commands.json generated'", {
          win         = { position = "float", border = "rounded" },
          interactive = false, -- don't auto-enter insert mode; keep open after command exits
        })
      end, { desc = "Generate compile_commands.json (for LSP)" })

      -- ── .clangd generator ─────────────────────────────────────────────────
      -- Cross-compilers (xtensa-gcc, avr-gcc, arm-none-eabi-gcc) pass flags
      -- that host clangd doesn't understand, causing false red errors.
      -- This writes a .clangd that strips the problematic ones.
      -- Covers: ESP32 (Xtensa + RISC-V), STM32/Pico (ARM), Arduino (AVR).
      vim.keymap.set("n", "<leader>iog", function()
        local content = [[
# .clangd — strip cross-compiler flags that confuse clangd
# Generated by Neovim IoT config. Re-run <leader>iog after changing boards.
# After running, do :LspRestart to pick up changes.
CompileFlags:
  Remove:
    # ── ESP32 Xtensa (ESP32, ESP32-S2) ──────────────────────────────────────
    - -mlongcalls
    - -mtext-section-literals
    - -mfix-esp32-psram-cache-issue
    # ── ESP32 RISC-V (ESP32-C3, ESP32-H2) ───────────────────────────────────
    - -mabi=ilp32
    # ── ARM Cortex-M (STM32, Raspberry Pi Pico / RP2040) ────────────────────
    - -mthumb-interwork
    - -mstrict-align
    # ── AVR (Arduino Uno, Mega, Nano) ────────────────────────────────────────
    - -mmcu=*
    # ── Generic embedded flags clangd chokes on ──────────────────────────────
    - -fno-tree-switch-conversion
    - -fno-jump-tables
    - --param=*
  Add:
    - -ferror-limit=0           # show all errors, not just the first N
Diagnostics:
  Suppress:
    - -Wunknown-warning-option
    - -Wunused-command-line-argument
]]
        local path = vim.fn.getcwd() .. "/.clangd"
        local f = io.open(path, "w")
        if f then
          f:write(content)
          f:close()
          vim.notify(
            ".clangd written to " .. path .. "\n→ run :LspRestart to apply",
            vim.log.levels.INFO,
            { title = "IoT / PlatformIO" }
          )
        else
          vim.notify("Could not write .clangd — check permissions", vim.log.levels.ERROR)
        end
      end, { desc = "Generate .clangd (suppress cross-compiler errors)" })
    end,
  },

  -- ─── Clangd Extensions — richer C/C++ LSP features ───────────────────────
  -- Adds on top of clangd (already installed via mason-lspconfig):
  --   gh               → switch between .h and .cpp instantly
  --   <leader>ioH      → type hierarchy (what implements this class?)
  --   <leader>ioT      → show AST for expression under cursor
  --   Inlay hints      → param names + type hints inline in C/C++ code
  {
    "p00f/clangd_extensions.nvim",
    ft = { "c", "cpp" },
    config = function()
      require("clangd_extensions").setup({
        inlay_hints = {
          inline             = true,
          only_current_line  = false,
          show_parameter_hints = true,
          parameter_hints_prefix = "  ",
          other_hints_prefix     = "  ",
        },
        ast = {
          role_icons = {
            type         = "",
            declaration  = "",
            expression   = "",
            specifier    = "",
            statement    = "",
            ["template argument"] = "",
          },
        },
        memory_usage = { border = "rounded" },
        symbol_info  = { border = "rounded" },
      })
    end,
    keys = {
      { "gh",          "<cmd>ClangdSwitchSourceHeader<cr>", ft = { "c", "cpp" }, desc = "Switch header/source" },
      { "<leader>ioH", "<cmd>ClangdTypeHierarchy<cr>",     ft = { "c", "cpp" }, desc = "Type hierarchy" },
      { "<leader>ioT", "<cmd>ClangdAST<cr>",               ft = { "c", "cpp" }, desc = "AST view" },
    },
  },
}
