-- Neotest: run tests without leaving Neovim
-- Supports Jest/Vitest (TS/JS), pytest (Python), Go test
return {
  {
    "nvim-neotest/neotest",
    dependencies = {
      "nvim-neotest/nvim-nio",
      "nvim-lua/plenary.nvim",
      "nvim-treesitter/nvim-treesitter",
      -- Adapters for your languages
      "nvim-neotest/neotest-jest",       -- TypeScript / JavaScript (Jest)
      "marilari88/neotest-vitest",       -- TypeScript / JavaScript (Vitest)
      "nvim-neotest/neotest-python",     -- Python (pytest)
      "fredrikaverpil/neotest-golang",   -- Go (newer, replaces neotest-go)
    },
    opts = {
      adapters = {
        -- Jest (detects jest.config.* automatically)
        ["neotest-jest"] = {
          jestCommand = "npx jest",
          jestConfigFile = function()
            local file = vim.fn.expand("%:p")
            local root = string.find(file, "/packages/")
              and string.match(file, "(.-/[^/]+/)src")
              or (vim.fn.getcwd() .. "/")
            for _, ext in ipairs({ "ts", "js", "mjs", "cjs" }) do
              local path = root .. "jest.config." .. ext
              if vim.fn.filereadable(path) == 1 then return path end
            end
          end,
          env = { CI = true },
        },
        -- Vitest (detects vitest.config.* automatically)
        ["neotest-vitest"] = {},
        -- Python pytest
        ["neotest-python"] = {
          dap = { justMyCode = false },
          runner = "pytest",
        },
        -- Go (-race removed: slow and breaks intentionally non-concurrent code)
        ["neotest-golang"] = {
          go_test_args = { "-count=1", "-timeout=60s" },
        },
      },
      -- Don't auto-open output panel — use <leader>to to check output when needed
      -- ("failed" is not a valid value; only true/false/"short" are supported)
      output = { open_on_run = false },
      status = { virtual_text = true }, -- show pass/fail inline in code
      icons = {
        passed  = " ",
        failed  = " ",
        running = " ",
        skipped = " ",
        unknown = " ",
      },
    },
    keys = {
      { "<leader>tt", function() require("neotest").run.run() end,                    desc = "Run nearest test" },
      { "<leader>tf", function() require("neotest").run.run(vim.fn.expand("%")) end,  desc = "Run all tests in file" },
      { "<leader>tl", function() require("neotest").run.run_last() end,               desc = "Re-run last test" },
      { "<leader>ts", function() require("neotest").summary.toggle() end,             desc = "Toggle test summary" },
      { "<leader>to", function() require("neotest").output_panel.toggle() end,        desc = "Toggle test output" },
      { "<leader>ta", function() require("neotest").run.run({ suite = true }) end,    desc = "Run all tests (suite)" },
      { "<leader>tS", function() require("neotest").run.stop() end,                   desc = "Stop test" },
      { "<leader>tW", function() require("neotest").run.run({ watch = true }) end,   desc = "Watch nearest test" },
      { "]f",         function() require("neotest").jump.next({ status = "failed" }) end, desc = "Next failed test" },
      { "[f",         function() require("neotest").jump.prev({ status = "failed" }) end, desc = "Prev failed test" },
      -- Run with coverage — generates the file that <leader>tc reads
      -- Python: requires pytest-cov  (pip install pytest-cov)
      -- Go:     writes /tmp/go-coverage.out
      { "<leader>tT", function()
          local ft = vim.bo.filetype
          local args
          if ft == "python" then
            args = { "--cov", "--cov-report=json:/tmp/coverage.json" }
          elseif ft == "go" then
            args = { "-coverprofile=/tmp/go-coverage.out" }
          end
          require("neotest").run.run({ vim.fn.expand("%"), extra_args = args })
        end, desc = "Run tests with coverage" },
    },
  },

  -- ─── Coverage — show test coverage as gutter signs + highlights ──────────────
  -- Reads coverage files generated by your test runner:
  --   Python: pytest --cov=. --cov-report=json:/tmp/coverage.json
  --   Go:     go test ./... -coverprofile=/tmp/go-coverage.out
  -- Then press <leader>tc to load and display inline.
  {
    "andythigpen/nvim-coverage",
    dependencies = { "nvim-lua/plenary.nvim" },
    cmd = { "CoverageLoad", "CoverageShow", "CoverageHide", "CoverageToggle", "CoverageSummary" },
    config = function()
      require("coverage").setup({
        commands = true,
        highlights = {
          covered   = { fg = "#98BB6C" }, -- kanagawa springGreen
          uncovered = { fg = "#E82424" }, -- kanagawa samuraiRed
          partial   = { fg = "#E6C384" }, -- kanagawa carpYellow
        },
        signs = {
          covered   = { hl = "CoverageCovered",   text = "▎" },
          uncovered = { hl = "CoverageUncovered", text = "▎" },
          partial   = { hl = "CoveragePartial",   text = "▎" },
        },
        summary = {
          min_coverage = 80.0, -- highlight files below 80% in the summary
        },
        lang = {
          go = {
            coverage_file = "/tmp/go-coverage.out",
          },
          python = {
            coverage_command = "coverage json -q -o /tmp/coverage.json",
            coverage_file    = "/tmp/coverage.json",
          },
        },
      })
    end,
    keys = {
      { "<leader>tc", "<cmd>CoverageToggle<cr>",  desc = "Toggle coverage" },
      { "<leader>tC", "<cmd>CoverageSummary<cr>", desc = "Coverage summary" },
    },
  },
}
